name: Feature Request
description: Suggest an idea or enhancement for this project
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving server-spin-up! 🚀

  - type: input
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: "Brief description of the requested feature"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        
        Example: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        A clear and concise description of what you want to happen.
        
        How should this feature work?
        What should the user experience be like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        A clear and concise description of any alternative solutions 
        or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature might be to implement?
      options:
        - Simple - Small change or addition
        - Medium - Moderate effort required  
        - Complex - Significant development needed
        - I'm not sure
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, mockups, or examples about the feature request here.
        Links to similar implementations in other projects are also helpful.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Intent
      description: Are you interested in helping implement this feature?
      options:
        - label: I'm willing to work on implementing this feature
        - label: I can help with testing once implemented
        - label: I can provide additional requirements/feedback during development

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution Guidelines
      options:
        - label: I have searched for similar feature requests before creating this one
          required: true
        - label: I have read the contributing guidelines
          required: true
